# Generated by Django 2.1.7 on 2019-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.PNG', upload_to='profile_pic'),
        ),
    ]
